brace_style = "PreferSameLine"

fn_single_line = true

format_strings = true

match_block_trailing_comma = true

max_width = 120

imports_granularity = "Module"
group_imports = "StdExternalCrate"

struct_field_align_threshold = 10
enum_discrim_align_threshold = 10

use_field_init_shorthand = true

wrap_comments = true