script_dir = "examples/scripts"

pcap_dir = "nbug.d/pcap"

interfaces = [ "lo", "wlp1s0" ]

srv_addr = "127.0.0.1:8081"

# Uncomment to allow any and all packets through the filter and into the
# resulting pcap
# filter = ""

# Defines how the network should behave for different types of traffic
# originating from this machine. Most protocols will have default behavior
# (tcp, udp, icmp); however, you may also define a specific command to run to
# mock sample network traffic. To do this specify the command with each
# argument as discrete elemnts of an array.
[[behaviors]]
dst = "127.0.0.1"
protocol = "icmp"

[[behaviors]]
dst = "8.8.8.8"
protocol = "icmp"
command = ["/usr/bin/ping", "-c", "1", "8.8.8.8"]