script_dir = "examples/scripts"

pcap_dir = "pcap"

interfaces = [ "lo", "wlp1s0" ]

srv_addr = "127.0.0.1:8081"

[[behaviors]]
dst = "localhost"
behavior_type = "icmp"

[[behaviors]]
dst = "8.8.8.8"
behavior_type = "icmp"
command = ["/usr/bin/ping", "-c", "1", "8.8.8.8"]