pcap_dir = "recv_pcap"

srv_addr = "127.0.0.1:8081"

[[behaviors]]
dst = "localhost"
protocol = "icmp"

[[behaviors]]
dst = "8.8.8.8"
sprotocol = "icmp"
command = ["/usr/bin/ping", "-c", "1", "8.8.8.8"]