pcap_dir = "nbug.d/recv_pcaps"

report_dir = "nbug.d/reports"

srv_addr = "0.0.0.0:8081"

[[behaviors]]
dst = "127.0.0.1"
protocol = "icmp"

[[behaviors]]
dst = "8.8.8.8"
protocol = "icmp"
command = ["/usr/bin/ping", "-c", "1", "8.8.8.8"]

# expectedd behaviors are specified same as done in the client; however, a
# source is not required. While a command can be specified for each behavior,
# it will be ignored.
[[behaviors]]
src = "127.0.0.1"
dst = "127.0.0.1"
protocol = "icmp"

[[behaviors]]
src = "192.168.0.10"
dst = "8.8.8.8"
protocol = "icmp"
command = ["/usr/bin/ping", "-c", "1", "8.8.8.8"]